-- Drop table if it exists
DROP TABLE IF EXISTS public.membership_inquiries;

-- Create the membership_inquiries table
CREATE TABLE public.membership_inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    plan TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    user_id UUID REFERENCES public.profiles(id)
);

-- Add comments to the columns
COMMENT ON COLUMN public.membership_inquiries.id IS 'Unique identifier for each membership inquiry';
COMMENT ON COLUMN public.membership_inquiries.name IS 'Name of the person inquiring';
COMMENT ON COLUMN public.membership_inquiries.email IS 'Email of the person inquiring';
COMMENT ON COLUMN public.membership_inquiries.phone IS 'Phone number of the person inquiring';
COMMENT ON COLUMN public.membership_inquiries.plan IS 'The membership plan the user is interested in';
COMMENT ON COLUMN public.membership_inquiries.created_at IS 'The date and time the inquiry was made';
COMMENT ON COLUMN public.membership_inquiries.user_id IS 'The user who made the inquiry, if they were logged in';

-- Enable Row-Level Security
ALTER TABLE public.membership_inquiries ENABLE ROW LEVEL SECURITY;

-- Create policies
-- Policy: Allow all users to insert a new inquiry
CREATE POLICY "Allow all users to insert an inquiry"
ON public.membership_inquiries
FOR INSERT
WITH CHECK (true);

-- Policy: Allow users to view their own inquiries
CREATE POLICY "Allow users to view their own inquiries"
ON public.membership_inquiries
FOR SELECT
USING (auth.uid() = user_id);

-- Note: Admin/staff access to view all inquiries would need to be handled separately,
-- typically by creating a service role key for a backend process or by defining
-- specific 'admin' roles in your database and creating a policy for that role.
-- For now, this allows any user to submit a form.
